In [19]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [20]:
np.random.seed(100)
print(np.random.rand(3))

[0.54340494 0.27836939 0.42451759]

In [21]:
customer_id=np.arange(1,101)

In [22]:
ages=np.random.randint(18,60,100)

In [23]:
income=np.random.randint(20000, 150000, 100)

In [24]:
spending_score=np.random.randint(1,101,100)

In [25]:
orders_per_month=np.random.randint(1,20,100)

In [26]:
gender=np.random.choice(['Male', 'Female', 'Other'], 100)

In [27]:
data={
    'customer_id' : customer_id,
    'age' : ages,
    'income' : income,
    'spending_score' : spending_score,
    'orders_per_month' : orders_per_month,
    'gender' : gender
}

In [28]:
df=pd.DataFrame(data)
df

    customer_id  age  income  spending_score  orders_per_month  gender
0             1   28   20429              54                16   Other
1             2   48  135491              18                18   Other
2             3   52   86576              66                11   Other
3             4   20  115756              43                 9    Male
4             5   52   93558              94                 9   Other
..          ...  ...     ...             ...               ...     ...
95           96   20  108755              93                19   Other
96           97   42  124368              53                13   Other
97           98   35  143634              45                18    Male
98           99   55   83485              14                 2  Female
99          100   43   53274              34                 3  Female

[100 rows x 6 columns]

In [29]:
df['Total_Spend_Estimate']=df['income']*df['spending_score']/100
df

,customer_id,age,income,spending_score,orders_per_month,gender,Total_Spend_Estimate
0,1,28,20429,54,16,Other,11031.66
1,2,48,135491,18,18,Other,24388.38
2,3,52,86576,66,11,Other,57140.16
3,4,20,115756,43,9,Male,49775.08
4,5,52,93558,94,9,Other,87944.52
...,...,...,...,...,...,...,...
95,96,20,108755,93,19,Other,101142.15
96,97,42,124368,53,13,Other,65915.04
97,98,35,143634,45,18,Male,64635.30
98,99,55,83485,14,2,Female,11687.90
99,100,43,53274,34,3,Female,18113.16

In [33]:
df['Category']=np.where(
    df['spending_score']>=70,
    'High',
     np.where(df['spending_score']>=40,
    'Medium',
    'Low'
             )
)
df

,customer_id,age,income,spending_score,orders_per_month,gender,Total_Spend_Estimate,Category
0,1,28,20429,54,16,Other,11031.66,Medium
1,2,48,135491,18,18,Other,24388.38,Low
2,3,52,86576,66,11,Other,57140.16,Medium
3,4,20,115756,43,9,Male,49775.08,Medium
4,5,52,93558,94,9,Other,87944.52,High
...,...,...,...,...,...,...,...,...
95,96,20,108755,93,19,Other,101142.15,High
96,97,42,124368,53,13,Other,65915.04,Medium
97,98,35,143634,45,18,Male,64635.30,Medium
98,99,55,83485,14,2,Female,11687.90,Low
99,100,43,53274,34,3,Female,18113.16,Low

In [36]:
a=df['income'].mean()
a

np.float64(87424.17)

In [39]:
b=df['spending_score'].median()
b

52.5

In [41]:
c=df['income'].std()
c

38272.65082764517

In [42]:
np.corrcoef(
    df['income'],
    df['spending_score']
)

array([[1.        , 0.08098286],
       [0.08098286, 1.        ]])

In [44]:
df.head()

,customer_id,age,income,spending_score,orders_per_month,gender,Total_Spend_Estimate,Category
0,1,28,20429,54,16,Other,11031.66,Medium
1,2,48,135491,18,18,Other,24388.38,Low
2,3,52,86576,66,11,Other,57140.16,Medium
3,4,20,115756,43,9,Male,49775.08,Medium
4,5,52,93558,94,9,Other,87944.52,High

In [45]:
df.nlargest(5, 'Total_Spend_Estimate')

,customer_id,age,income,spending_score,orders_per_month,gender,Total_Spend_Estimate,Category
15,16,45,141544,100,4,Female,141544.00,High
44,45,26,145313,93,16,Other,135141.09,High
92,93,57,141655,88,1,Male,124656.40,High
19,20,31,144562,82,17,Female,118540.84,High
54,55,18,140786,83,16,Female,116852.38,High

In [47]:
df.groupby('gender')['income'].mean()

gender
Female    94853.914286
Male      87907.218750
Other     79075.727273
Name: income, dtype: float64